### ISSUE TITLE
Multiple sheets functionality for DownloadXLSX()

### ISSUE THREAD

**Issue by bonnfire** [Displayr/flipAPI#5]
Hey! Thanks so much for this package. 
I've got this Dropbox link that I'm loading data from and it works great for the first sheet (the default parameter), but I'd like to load the data from multiple sheets. Do you have a readxl::excel_sheets() parallel that would be helpful? Or is there some map() workaround that you could suggest?

**Comment by chschan** [comment]
You should be able to read multiple sheets by changing the `sheets` argument. If you want to read them in one go, you could try `lapply(1:n, function(i) DownloadXLSX(<url>, sheet = i))`

**Comment by bonnfire** [comment]
Thanks so much! 
On top of this, I wanted to implement a more robust extraction of n but wasn't able to use gdata::sheetCount() with the https: url as the argument. Any tips on that front?

**Comment by bonnfire** [comment]
I set a higher number than the actual number of sheets and got the error message "Can't retrieve sheet in position 25, only 24 sheet(s) found.", so I'm wondering if there is some way to explicitly generate this "24" number.

**Comment by chschan** [comment]
I'm not sure how you find the actual number, but you could just try it inside a loop. Something like this maybe?
```
i <- 1
while (TRUE)
{
    res[[i]] <- try(DownloadXLSX(<url>, sheet = i))
    if (inherits(res[[i]], "try-error"))
        break
    i <- i + 1
}
```

**Comment by bonnfire** [comment]
Yes! Thank you so much! 
Never would have thought about the inherits() function... I really appreciate it. This gets the job done for me.
